<html>
    <body>
        <?php 
            if (isset($flash['success'])) {
                foreach ($flash['success'] as $message) {
                    print_r($message);
                }
            }
        ?>
        <form action="/users" method="get">
            <input type="search" name="term" value=<?=isset($term) ? $term : ''?>>
        </form>
    </body>

    <table  иborder-style="solid" border="11">
        <tr>
            <th>id</th>
            <th>Имя</th>
            <th>Почта</th>
        </tr>
        <?php foreach ($users as $user): ?>        
            <tr>    
                <td><?= $user->getId() ?></td>
                <td><?= "<a href='/users/" . $user->getId() . "/edit'>" . $user->getName() . "</a>"?></td>
                <td><?= $user->getEmail()?></td>
            </tr>
        <?php endforeach ?>
    </table>
    <hr>
    <form action="/users/new" method="get">
    <input type="submit" value="Добавить">
</form>
</html>