<form action = "/users" method="post">
    <div>
            <label>
                <h1>Имя</h1>
                <input type="text" name="user[name]" required value=<?= htmlspecialchars($user['name']) ?>> 
                <?= '<p>' . ($errors['name'] ?? "") . '<p>'?>
            </label>
    </div>
    <div>
            <label>
                <h1>Электронная почта</h1>
                <input type="text" name="user[email]" required value=<?= htmlspecialchars($user['email']) ?>>
                <?= '<p>' . ($errors['email'] ?? "") . '<p>'?>
            </label>
    </div>
    <div>
            <label>
                <input type="submit" value="Добавить" > 
            </label>
    </div>

</form>

